[package]
name = "example"
version ="0.2.7"
edition = "2021"
publish = false
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.3.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
parse-display = "0.8.0"
sqlx = { version = "0.6.2", features = ["runtime-actix-rustls", "postgres", "chrono", "uuid", "json"] }
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
nanoid = "0.4.0"
thiserror = "1.0.38"
futures = "0.3.26"
validator = { version = "0.16.0", features = ["derive"] }
evento = { path = "../evento" }

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]

[dependencies.mongodb]
version = "2.3.1"
features = ["tokio-runtime"]
