branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@timada/semantic-release-cargo"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo update"
  - path: "@semantic-release/git"
    assets:
      - "**/Cargo.toml"
      - Cargo.lock
