[workspace]
resolver = "2"

members = [
    "./evento",
    "./evento-test",
    "./evento-core",
    "./evento-sql",
    "./evento-sql-migrator",
    "./evento-macro",
    "./evento-fjall",
    "./evento-accord",
    "./evento-remote",
    "./examples/*"
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/timayz/evento"
keywords = ["event-sourcing", "cqrs", "ddd", "events", "eventstore"]
categories = ["database", "asynchronous"]

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.dependencies]
# Internal crates 
evento = { path = "./evento" }
evento-test = { path = "./evento-test" }
evento-core = { path = "./evento-core" }
evento-sql = { path = "./evento-sql" }
evento-sql-migrator = { path = "./evento-sql-migrator" }
evento-macro = { path = "./evento-macro" }
evento-fjall = { path = "./evento-fjall" }
evento-accord = { path = "./evento-accord" }
evento-remote = { path = "./evento-remote" }
bank = { path = "./examples/bank" }

# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
bitcode = "0.6"
thiserror = "2.0"
tracing = "0.1"
base64 = "0.23"
once_cell = "1"
sha3 = "0.12"
hex = "0.4"

# Async runtime
tokio = { version = "1.52", features = ["full"] }
futures-util = "0.3"
backon = "1.6"

# Serialization
serde = { version = "1.0", features = ["derive"] }
ulid = { version = "3.0", features = ["serde"] }

# Database
sqlx = { version = "0.9" }
sqlx_migrator = "0.19"
sea-query = { version = "1.0.1", default-features = false, features = ["derive", "audit"] }
sea-query-sqlx = { version = "0.9.1", features = ["runtime-tokio"] }
fjall = "3.1"

# Proc macro
quote = "1.0"
convert_case = "0.12"
syn = { version = "3.0.0", features = ["full", "parsing", "extra-traits"] }

# Web
axum = "0.8"
askama = "0.16"

# Testing
rand = "0.10"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
