version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  pulsar:
    image: apachepulsar/pulsar:2.10.2
    command: bin/pulsar standalone
    ports:
      - 6650:6650