version: '3.9'

services:
  postgres:
    image: postgres:17.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  mongo:
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
