[package]
name = "bank-axum-fjall"
version = "2.0.0-alpha.28"
edition.workspace = true
publish = false

[dependencies]
bank.workspace = true
evento = { workspace = true, features = ["fjall"] }
axum.workspace = true
askama.workspace = true
tokio.workspace = true
serde.workspace = true
ulid.workspace = true
anyhow.workspace = true
tempfile = "3.27"
