[package]
name = "evento-axum"
version = "0.6.1"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "A collection of libraries and tools that help you build DDD, CQRS, and event sourcing."
repository = "https://github.com/timayz/evento"
documentation = "https://docs.rs/evento"

[dependencies]
serde = "1.0.183"
serde_json = "1.0.104"
axum = { version = "0.6.20" }
anyhow = "1.0.74"
