[package]
name = "evento-axum"
version = "1.0.0-alpha.1"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "A collection of libraries and tools that help you build DDD, CQRS, and event sourcing."
repository = "https://github.com/timayz/evento"
documentation = "https://docs.rs/evento"

[dependencies]
serde = "1.0.189"
axum = { version = "0.6.20" }
async-trait = "0.1.73"
thiserror = "1.0.49"
validator = "0.16.1"
tracing = "0.1.39"
evento = { path = "../evento", version = "1.0.0-alpha.1" }
evento-store = { path = "../evento-store", version = "1.0.0-alpha.1" }
http = "0.2.9"
