[package]
name = "evento-query"
version = "0.10.2"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "Helper for cursor query"
repository = "https://github.com/timayz/evento"
documentation = "https://docs.rs/evento"

[features]
default = []

[dependencies]


[dev-dependencies]

