[package]
name = "evento-query"
version = "0.9.1"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "A collection of libraries and tools that help you build DDD, CQRS, and event sourcing."
repository = "https://github.com/timayz/evento"
documentation = "https://docs.rs/evento"

[dependencies]
serde = "1.0.188"
sqlx = { version = "0.7.2", features = ["runtime-tokio", "postgres", "chrono", "uuid", "json"] }
thiserror = "1.0.49"
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde"] }
futures-util = "0.3.28"
base64 = "0.21.4"
harsh = "0.2.2"

[dev-dependencies]
evento-store = { path = "../evento-store" }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
sqlx = { version = "0.7.2", features = ["runtime-tokio", "postgres", "chrono", "uuid", "json", "any"] }
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "macro-diagnostics" ]}
parse-display = { version = "0.8.2" }
