[package]
name = "evento-query"
version = "0.9.0"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "A collection of libraries and tools that help you build DDD, CQRS, and event sourcing."
repository = "https://github.com/timayz/evento"
documentation = "https://docs.rs/evento"

[dependencies]
serde = "1.0.188"
serde_json = "1.0.107"
parking_lot = "0.12.1"
sqlx = { version = "0.7.2", features = ["runtime-tokio", "postgres", "chrono", "uuid", "json"] }
thiserror = "1.0.49"
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde"] }
tracing = "0.1.37"
tokio = "1.32.0"
futures-util = "0.3.28"
validator = { version = "0.16.1", optional = true, features = ["derive"] }
base64 = "0.21.4"
harsh = "0.2.2"
glob-match = "0.2.1"
evento = { path = "../evento", version = "0.9.0" }

[dependencies.uuid]
version = "1.4.1"
features = [
	"v4",
	"fast-rng",
	"macro-diagnostics",
	"serde",
]

[dev-dependencies]
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
sqlx = { version = "0.7.2", features = ["runtime-tokio", "postgres", "chrono", "uuid", "json", "any"] }
parse-display = { version = "0.8.2" }
evento-store = { path = "../evento-store" }
