use proc_macro::TokenStream;
use quote::quote;
use syn::{DeriveInput, Error, Ident, Result};

/// Parsed mode for `#[evento::snapshot(none | memory)]`.
enum SnapshotMode {
    /// Opt out of snapshotting entirely (empty `Snapshot` impl).
    None,
    /// In-memory `RwLock<HashMap>` snapshot store keyed by aggregate id.
    Memory,
}

pub fn snapshot_impl(attr: TokenStream, input: &DeriveInput) -> Result<TokenStream> {
    let mode: Ident = syn::parse(attr).map_err(|e| {
        Error::new(
            e.span(),
            "expected a snapshot mode: `#[evento::snapshot(none)]` or `#[evento::snapshot(memory)]`",
        )
    })?;
    let mode = match mode.to_string().as_str() {
        "none" => SnapshotMode::None,
        "memory" => SnapshotMode::Memory,
        other => {
            return Err(Error::new(
                mode.span(),
                format!("unknown snapshot mode `{other}`; expected `none` or `memory`"),
            ));
        }
    };

    let name = &input.ident;
    let vis = &input.vis;
    let (_, ty_generics, where_clause) = input.generics.split_for_impl();

    // The impl is generic over the executor in addition to the struct's own
    // generic parameters.
    let mut impl_generics = input.generics.clone();
    impl_generics
        .params
        .push(syn::parse_quote!(EventoExecutor: ::evento::Executor));
    let (impl_generics, _, _) = impl_generics.split_for_impl();
    let impl_generics = quote! { #impl_generics };

    let tokens = match mode {
        SnapshotMode::None => quote! {
            #input

            impl #impl_generics ::evento::projection::Snapshot<EventoExecutor>
                for #name #ty_generics #where_clause {}
        },
        SnapshotMode::Memory => {
            if !input.generics.params.is_empty() {
                return Err(Error::new_spanned(
                    &input.generics,
                    "`#[evento::snapshot(memory)]` does not support generic structs",
                ));
            }

            quote! {
                #input

                impl #name {
                    /// In-memory snapshot store generated by `#[evento::snapshot(memory)]`,
                    /// keyed by aggregate id.
                    #vis fn snapshot_rows()
                    -> &'static ::std::sync::RwLock<::std::collections::HashMap<String, Self>> {
                        static ROWS: ::std::sync::OnceLock<
                            ::std::sync::RwLock<::std::collections::HashMap<String, #name>>,
                        > = ::std::sync::OnceLock::new();
                        ROWS.get_or_init(::std::default::Default::default)
                    }
                }

                impl<EventoExecutor: ::evento::Executor> ::evento::projection::Snapshot<EventoExecutor> for #name {
                    async fn restore(
                        context: &::evento::projection::Context<'_, EventoExecutor>,
                    ) -> ::anyhow::Result<Option<Self>> {
                        Ok(Self::snapshot_rows().read().unwrap().get(&context.id).cloned())
                    }

                    async fn take_snapshot(
                        &self,
                        context: &::evento::projection::Context<'_, EventoExecutor>,
                    ) -> ::anyhow::Result<()> {
                        Self::snapshot_rows()
                            .write()
                            .unwrap()
                            .insert(context.id.clone(), self.clone());
                        Ok(())
                    }

                    async fn drop_snapshot(
                        context: &::evento::projection::Context<'_, EventoExecutor>,
                    ) -> ::anyhow::Result<()> {
                        Self::snapshot_rows().write().unwrap().remove(&context.id);
                        Ok(())
                    }
                }
            }
        }
    };

    Ok(tokens.into())
}
