[package]
name = "payment"
version = "1.0.0-alpha.4"
edition = "2021"

[dependencies]
askama = { version = "0.12.1", default-features = false, features = ["with-axum", "mime", "mime_guess"] }
askama_axum = "0.3.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
axum = "0.6.20"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.14"
futures = "0.3.29"
http = "0.2.9"
sqlx = { version = "0.7.2", features = [ "runtime-tokio", "tls-rustls", "postgres", "chrono", "uuid", "json", "any" ] }
anyhow = "1.0.75"
rust-embed = "8.0.0"
mime_guess = "2.0.4"
evento = { path = "../../evento", version = "1.0.0-alpha.4", features = ["pg"] }
evento-axum = { path = "../../evento-axum", version = "1.0.0-alpha.4" }
