[package]
name = "evento"
version = "2.0.0-alpha.17"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
description = "Event sourcing and CQRS toolkit with SQL persistence, projections, and subscriptions"
documentation = "https://docs.rs/evento"
readme = "README.md"

[dependencies]
evento-core = { path = "../evento-core", version = "2.0.0-alpha.17" }
evento-sql = { path = "../evento-sql", optional = true, version = "2.0.0-alpha.17" }
evento-sql-migrator = { path = "../evento-sql-migrator", optional = true, version = "2.0.0-alpha.17" }
sqlx_migrator = { workspace = true, optional = true }

[features]
default = ["macro"]
macro = ["evento-core/macro"]
group = ["evento-core/group"]
rw = ["evento-core/rw"]
sql = ["sqlite", "mysql", "postgres"]
sqlite = ["evento-sql/sqlite", "evento-sql-migrator/sqlite", "sqlx_migrator/sqlite"]
mysql = ["evento-sql/mysql", "evento-sql-migrator/mysql", "sqlx_migrator/mysql"]
postgres = ["evento-sql/postgres", "evento-sql-migrator/postgres", "sqlx_migrator/postgres"]
