[package]
name = "evento-store"
version ="0.5.7"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "A collection of libraries and tools that help you build DDD, CQRS, and event sourcing."
repository = "https://github.com/timayz/evento"
documentation = "https://docs.rs/evento"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.183"
serde_json = "1.0.104"
parking_lot = "0.12.1"
sqlx = { version = "0.7.1", features = ["runtime-tokio", "postgres", "chrono", "uuid", "json"] }
thiserror = "1.0.46"
chrono = { version = "0.4.26", default-features = false, features = ["clock", "serde"] }
futures-util = "0.3.28"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]

[dev-dependencies]
tokio = { version = "1.31.0", features = ["rt-multi-thread", "macros"] }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio", "postgres", "chrono", "uuid", "json", "any"] }
parse-display = { version = "0.8.2" }
