// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: evento/v1/store.proto

package eventov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStore_Write_FullMethodName           = "/evento.v1.EventStore/Write"
	EventStore_Read_FullMethodName            = "/evento.v1.EventStore/Read"
	EventStore_LatestTimestamp_FullMethodName = "/evento.v1.EventStore/LatestTimestamp"
	EventStore_Subscribe_FullMethodName       = "/evento.v1.EventStore/Subscribe"
	EventStore_GetSnapshot_FullMethodName     = "/evento.v1.EventStore/GetSnapshot"
	EventStore_SaveSnapshot_FullMethodName    = "/evento.v1.EventStore/SaveSnapshot"
	EventStore_DeleteSnapshot_FullMethodName  = "/evento.v1.EventStore/DeleteSnapshot"
)

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC surface for the raw evento event store (v1).
//
// This service exposes evento's `Executor` write/read paths over the wire so
// non-Rust clients can use evento as an event store. Higher-level ergonomics
// (aggregate replay, projections, subscriptions) are reimplemented client-side.
//
// Conventions:
//   - Event `data` and `Metadata.meta` values are OPAQUE bytes; the server is
//     encoding-agnostic (bitcode framing is purely a Rust-client concern).
//   - ULIDs and pagination cursors are strings, never decoded server-side.
//   - Fields that map to a Rust `u16` use `uint32` with server-side range
//     validation (`<= 65535`).
//   - `optional string` is used wherever the Rust type is `Option<String>` so
//     "absent" is distinguishable from "present but empty".
type EventStoreClient interface {
	// Appends events to a (possibly new) aggregate. The server assigns each
	// event's id (ULID), version (original_version+1..), and timestamp.
	//
	// Optimistic concurrency: if `original_version` does not match the
	// aggregate's current version, returns FAILED_PRECONDITION with the error
	// detail reason "INVALID_ORIGINAL_VERSION".
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// Cursor-paginated query over stored events.
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Timestamp (unix seconds) of the most recent matching event; 0 if none.
	LatestTimestamp(ctx context.Context, in *LatestTimestampRequest, opts ...grpc.CallOption) (*LatestTimestampResponse, error)
	// Durable, resumable event subscription (at-least-once delivery).
	//
	// The client opens the stream with a `SubscribeStart`; the server replays
	// from the subscription key's saved cursor and then tails live events,
	// pushing `EventBatch` messages. After each batch the client sends a
	// `SubscribeAck` with the last cursor it processed, and the server persists
	// that cursor — so a reconnect resumes where it left off rather than
	// redelivering everything. Only one stream per key is active at a time
	// (last writer wins); a superseded stream ends.
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, EventBatch], error)
	// Returns the snapshot for (aggregate_type, aggregate_revision, id), or none
	// if absent — including when the stored revision differs (forcing a rebuild).
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	// Upserts the snapshot for (aggregate_type, id) — one row per aggregate.
	SaveSnapshot(ctx context.Context, in *SaveSnapshotRequest, opts ...grpc.CallOption) (*SaveSnapshotResponse, error)
	// Deletes the snapshot for (aggregate_type, id). Idempotent.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
}

type eventStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStoreClient(cc grpc.ClientConnInterface) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, EventStore_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, EventStore_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) LatestTimestamp(ctx context.Context, in *LatestTimestampRequest, opts ...grpc.CallOption) (*LatestTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestTimestampResponse)
	err := c.cc.Invoke(ctx, EventStore_LatestTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, EventBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[0], EventStore_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, EventBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_SubscribeClient = grpc.BidiStreamingClient[SubscribeRequest, EventBatch]

func (c *eventStoreClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, EventStore_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) SaveSnapshot(ctx context.Context, in *SaveSnapshotRequest, opts ...grpc.CallOption) (*SaveSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSnapshotResponse)
	err := c.cc.Invoke(ctx, EventStore_SaveSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, EventStore_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServer is the server API for EventStore service.
// All implementations must embed UnimplementedEventStoreServer
// for forward compatibility.
//
// gRPC surface for the raw evento event store (v1).
//
// This service exposes evento's `Executor` write/read paths over the wire so
// non-Rust clients can use evento as an event store. Higher-level ergonomics
// (aggregate replay, projections, subscriptions) are reimplemented client-side.
//
// Conventions:
//   - Event `data` and `Metadata.meta` values are OPAQUE bytes; the server is
//     encoding-agnostic (bitcode framing is purely a Rust-client concern).
//   - ULIDs and pagination cursors are strings, never decoded server-side.
//   - Fields that map to a Rust `u16` use `uint32` with server-side range
//     validation (`<= 65535`).
//   - `optional string` is used wherever the Rust type is `Option<String>` so
//     "absent" is distinguishable from "present but empty".
type EventStoreServer interface {
	// Appends events to a (possibly new) aggregate. The server assigns each
	// event's id (ULID), version (original_version+1..), and timestamp.
	//
	// Optimistic concurrency: if `original_version` does not match the
	// aggregate's current version, returns FAILED_PRECONDITION with the error
	// detail reason "INVALID_ORIGINAL_VERSION".
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	// Cursor-paginated query over stored events.
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// Timestamp (unix seconds) of the most recent matching event; 0 if none.
	LatestTimestamp(context.Context, *LatestTimestampRequest) (*LatestTimestampResponse, error)
	// Durable, resumable event subscription (at-least-once delivery).
	//
	// The client opens the stream with a `SubscribeStart`; the server replays
	// from the subscription key's saved cursor and then tails live events,
	// pushing `EventBatch` messages. After each batch the client sends a
	// `SubscribeAck` with the last cursor it processed, and the server persists
	// that cursor — so a reconnect resumes where it left off rather than
	// redelivering everything. Only one stream per key is active at a time
	// (last writer wins); a superseded stream ends.
	Subscribe(grpc.BidiStreamingServer[SubscribeRequest, EventBatch]) error
	// Returns the snapshot for (aggregate_type, aggregate_revision, id), or none
	// if absent — including when the stored revision differs (forcing a rebuild).
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	// Upserts the snapshot for (aggregate_type, id) — one row per aggregate.
	SaveSnapshot(context.Context, *SaveSnapshotRequest) (*SaveSnapshotResponse, error)
	// Deletes the snapshot for (aggregate_type, id). Idempotent.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	mustEmbedUnimplementedEventStoreServer()
}

// UnimplementedEventStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStoreServer struct{}

func (UnimplementedEventStoreServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedEventStoreServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedEventStoreServer) LatestTimestamp(context.Context, *LatestTimestampRequest) (*LatestTimestampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LatestTimestamp not implemented")
}
func (UnimplementedEventStoreServer) Subscribe(grpc.BidiStreamingServer[SubscribeRequest, EventBatch]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEventStoreServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedEventStoreServer) SaveSnapshot(context.Context, *SaveSnapshotRequest) (*SaveSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSnapshot not implemented")
}
func (UnimplementedEventStoreServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedEventStoreServer) mustEmbedUnimplementedEventStoreServer() {}
func (UnimplementedEventStoreServer) testEmbeddedByValue()                    {}

// UnsafeEventStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStoreServer will
// result in compilation errors.
type UnsafeEventStoreServer interface {
	mustEmbedUnimplementedEventStoreServer()
}

func RegisterEventStoreServer(s grpc.ServiceRegistrar, srv EventStoreServer) {
	// If the following call panics, it indicates UnimplementedEventStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStore_ServiceDesc, srv)
}

func _EventStore_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_LatestTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).LatestTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_LatestTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).LatestTimestamp(ctx, req.(*LatestTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventStoreServer).Subscribe(&grpc.GenericServerStream[SubscribeRequest, EventBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_SubscribeServer = grpc.BidiStreamingServer[SubscribeRequest, EventBatch]

func _EventStore_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_SaveSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).SaveSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_SaveSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).SaveSnapshot(ctx, req.(*SaveSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventStore_ServiceDesc is the grpc.ServiceDesc for EventStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evento.v1.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _EventStore_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _EventStore_Read_Handler,
		},
		{
			MethodName: "LatestTimestamp",
			Handler:    _EventStore_LatestTimestamp_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _EventStore_GetSnapshot_Handler,
		},
		{
			MethodName: "SaveSnapshot",
			Handler:    _EventStore_SaveSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _EventStore_DeleteSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _EventStore_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "evento/v1/store.proto",
}
