// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evento/v1/store.proto

package eventov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ULID
	AggregateId     string                 `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType   string                 `protobuf:"bytes,3,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	Version         uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // logical u16; server validates <= 65535
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	RoutingKey      *string                `protobuf:"bytes,6,opt,name=routing_key,json=routingKey,proto3,oneof" json:"routing_key,omitempty"`
	Data            []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"` // opaque payload
	Metadata        *Metadata              `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // unix seconds
	TimestampSubsec uint32                 `protobuf:"varint,10,opt,name=timestamp_subsec,json=timestampSubsec,proto3" json:"timestamp_subsec,omitempty"` // milliseconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_evento_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Event) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *Event) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetRoutingKey() string {
	if x != nil && x.RoutingKey != nil {
		return *x.RoutingKey
	}
	return ""
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetTimestampSubsec() uint32 {
	if x != nil {
		return x.TimestampSubsec
	}
	return 0
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                               // metadata ULID; server-assigned if empty
	Meta          map[string][]byte      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // opaque pairs (e.g. EVENTO_REQUESTED_BY)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_evento_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetMeta() map[string][]byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

// One event to append. The server assigns id/version/timestamp.
type NewEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // opaque payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewEvent) Reset() {
	*x = NewEvent{}
	mi := &file_evento_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEvent) ProtoMessage() {}

func (x *NewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEvent.ProtoReflect.Descriptor instead.
func (*NewEvent) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{2}
}

func (x *NewEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateType string                 `protobuf:"bytes,1,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	// Omit/empty to create a new aggregate (server generates a ULID id).
	AggregateId *string `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3,oneof" json:"aggregate_id,omitempty"`
	// Expected current version for optimistic concurrency. 0 == new aggregate.
	OriginalVersion uint32  `protobuf:"varint,3,opt,name=original_version,json=originalVersion,proto3" json:"original_version,omitempty"` // logical u16; validated
	RoutingKey      *string `protobuf:"bytes,4,opt,name=routing_key,json=routingKey,proto3,oneof" json:"routing_key,omitempty"`
	// Metadata applied to every event in this write. `id` may be empty (server fills).
	Metadata      *Metadata   `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Events        []*NewEvent `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"` // must be non-empty (else INVALID_ARGUMENT)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_evento_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequest) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *WriteRequest) GetAggregateId() string {
	if x != nil && x.AggregateId != nil {
		return *x.AggregateId
	}
	return ""
}

func (x *WriteRequest) GetOriginalVersion() uint32 {
	if x != nil {
		return x.OriginalVersion
	}
	return 0
}

func (x *WriteRequest) GetRoutingKey() string {
	if x != nil && x.RoutingKey != nil {
		return *x.RoutingKey
	}
	return ""
}

func (x *WriteRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WriteRequest) GetEvents() []*NewEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`  // the (possibly generated) aggregate id
	LastVersion   uint32                 `protobuf:"varint,2,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"` // version of the last appended event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_evento_v1_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{4}
}

func (x *WriteResponse) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *WriteResponse) GetLastVersion() uint32 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

type EventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateType string                 `protobuf:"bytes,1,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateId   *string                `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3,oneof" json:"aggregate_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_evento_v1_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{5}
}

func (x *EventFilter) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *EventFilter) GetAggregateId() string {
	if x != nil && x.AggregateId != nil {
		return *x.AggregateId
	}
	return ""
}

func (x *EventFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Mirrors evento's RoutingKey enum (All | Value(Option<String>)):
//   - all = true                -> RoutingKey::All
//   - all = false, no value      -> RoutingKey::Value(None)
//   - all = false, value = "x"   -> RoutingKey::Value(Some("x"))
//
// Omitting the whole RoutingKey message -> None (no routing filter).
type RoutingKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingKey) Reset() {
	*x = RoutingKey{}
	mi := &file_evento_v1_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingKey) ProtoMessage() {}

func (x *RoutingKey) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingKey.ProtoReflect.Descriptor instead.
func (*RoutingKey) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{6}
}

func (x *RoutingKey) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *RoutingKey) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// Cursor pagination (GraphQL-style): first/after OR last/before.
type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         *uint32                `protobuf:"varint,1,opt,name=first,proto3,oneof" json:"first,omitempty"`  // logical u16
	After         *string                `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"`   // opaque cursor (base64)
	Last          *uint32                `protobuf:"varint,3,opt,name=last,proto3,oneof" json:"last,omitempty"`    // logical u16
	Before        *string                `protobuf:"bytes,4,opt,name=before,proto3,oneof" json:"before,omitempty"` // opaque cursor (base64)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_evento_v1_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{7}
}

func (x *Args) GetFirst() uint32 {
	if x != nil && x.First != nil {
		return *x.First
	}
	return 0
}

func (x *Args) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *Args) GetLast() uint32 {
	if x != nil && x.Last != nil {
		return *x.Last
	}
	return 0
}

func (x *Args) GetBefore() string {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return ""
}

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty list -> None (read everything, no aggregate filter).
	Aggregators   []*EventFilter `protobuf:"bytes,1,rep,name=aggregators,proto3" json:"aggregators,omitempty"`
	RoutingKey    *RoutingKey    `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3,oneof" json:"routing_key,omitempty"`
	Args          *Args          `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_evento_v1_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{8}
}

func (x *ReadRequest) GetAggregators() []*EventFilter {
	if x != nil {
		return x.Aggregators
	}
	return nil
}

func (x *ReadRequest) GetRoutingKey() *RoutingKey {
	if x != nil {
		return x.RoutingKey
	}
	return nil
}

func (x *ReadRequest) GetArgs() *Args {
	if x != nil {
		return x.Args
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // opaque
	Node          *Event                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_evento_v1_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{9}
}

func (x *Edge) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Edge) GetNode() *Event {
	if x != nil {
		return x.Node
	}
	return nil
}

type PageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasPreviousPage bool                   `protobuf:"varint,1,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,2,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	StartCursor     *string                `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3,oneof" json:"start_cursor,omitempty"`
	EndCursor       *string                `protobuf:"bytes,4,opt,name=end_cursor,json=endCursor,proto3,oneof" json:"end_cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_evento_v1_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{10}
}

func (x *PageInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil && x.StartCursor != nil {
		return *x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil && x.EndCursor != nil {
		return *x.EndCursor
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*Edge                `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_evento_v1_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{11}
}

func (x *ReadResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ReadResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type LatestTimestampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggregators   []*EventFilter         `protobuf:"bytes,1,rep,name=aggregators,proto3" json:"aggregators,omitempty"` // empty -> None
	RoutingKey    *RoutingKey            `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3,oneof" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestTimestampRequest) Reset() {
	*x = LatestTimestampRequest{}
	mi := &file_evento_v1_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTimestampRequest) ProtoMessage() {}

func (x *LatestTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTimestampRequest.ProtoReflect.Descriptor instead.
func (*LatestTimestampRequest) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{12}
}

func (x *LatestTimestampRequest) GetAggregators() []*EventFilter {
	if x != nil {
		return x.Aggregators
	}
	return nil
}

func (x *LatestTimestampRequest) GetRoutingKey() *RoutingKey {
	if x != nil {
		return x.RoutingKey
	}
	return nil
}

type LatestTimestampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestTimestampResponse) Reset() {
	*x = LatestTimestampResponse{}
	mi := &file_evento_v1_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTimestampResponse) ProtoMessage() {}

func (x *LatestTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTimestampResponse.ProtoReflect.Descriptor instead.
func (*LatestTimestampResponse) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{13}
}

func (x *LatestTimestampResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Opens a subscription. Sent once, as the first message on the stream.
type SubscribeStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Durable subscription identity; its cursor persists across reconnects.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Optional event filters (empty -> all events).
	Aggregators []*EventFilter `protobuf:"bytes,2,rep,name=aggregators,proto3" json:"aggregators,omitempty"`
	RoutingKey  *RoutingKey    `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3,oneof" json:"routing_key,omitempty"`
	// Max events per pushed batch (logical u16; 0 -> server default).
	ChunkSize     uint32 `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeStart) Reset() {
	*x = SubscribeStart{}
	mi := &file_evento_v1_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStart) ProtoMessage() {}

func (x *SubscribeStart) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStart.ProtoReflect.Descriptor instead.
func (*SubscribeStart) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeStart) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SubscribeStart) GetAggregators() []*EventFilter {
	if x != nil {
		return x.Aggregators
	}
	return nil
}

func (x *SubscribeStart) GetRoutingKey() *RoutingKey {
	if x != nil {
		return x.RoutingKey
	}
	return nil
}

func (x *SubscribeStart) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

// Acknowledges processing up to (and including) `cursor`. Sent after each batch.
type SubscribeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // opaque; the last processed event's cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAck) Reset() {
	*x = SubscribeAck{}
	mi := &file_evento_v1_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAck) ProtoMessage() {}

func (x *SubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAck.ProtoReflect.Descriptor instead.
func (*SubscribeAck) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{15}
}

func (x *SubscribeAck) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SubscribeRequest_Start
	//	*SubscribeRequest_Ack
	Message       isSubscribeRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_evento_v1_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeRequest) GetMessage() isSubscribeRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SubscribeRequest) GetStart() *SubscribeStart {
	if x != nil {
		if x, ok := x.Message.(*SubscribeRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *SubscribeRequest) GetAck() *SubscribeAck {
	if x != nil {
		if x, ok := x.Message.(*SubscribeRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isSubscribeRequest_Message interface {
	isSubscribeRequest_Message()
}

type SubscribeRequest_Start struct {
	Start *SubscribeStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type SubscribeRequest_Ack struct {
	Ack *SubscribeAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*SubscribeRequest_Start) isSubscribeRequest_Message() {}

func (*SubscribeRequest_Ack) isSubscribeRequest_Message() {}

type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*Edge                `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_evento_v1_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{17}
}

func (x *EventBatch) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`     // opaque serialized projection state
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // opaque; the position the snapshot is valid up to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_evento_v1_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{18}
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Snapshot) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AggregateType     string                 `protobuf:"bytes,1,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateRevision string                 `protobuf:"bytes,2,opt,name=aggregate_revision,json=aggregateRevision,proto3" json:"aggregate_revision,omitempty"`
	Id                string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_evento_v1_store_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{19}
}

func (x *GetSnapshotRequest) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *GetSnapshotRequest) GetAggregateRevision() string {
	if x != nil {
		return x.AggregateRevision
	}
	return ""
}

func (x *GetSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof" json:"snapshot,omitempty"` // absent if none for (type, revision, id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_evento_v1_store_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{20}
}

func (x *GetSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type SaveSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AggregateType     string                 `protobuf:"bytes,1,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateRevision string                 `protobuf:"bytes,2,opt,name=aggregate_revision,json=aggregateRevision,proto3" json:"aggregate_revision,omitempty"`
	Id                string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data              []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Cursor            string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SaveSnapshotRequest) Reset() {
	*x = SaveSnapshotRequest{}
	mi := &file_evento_v1_store_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotRequest) ProtoMessage() {}

func (x *SaveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SaveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{21}
}

func (x *SaveSnapshotRequest) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *SaveSnapshotRequest) GetAggregateRevision() string {
	if x != nil {
		return x.AggregateRevision
	}
	return ""
}

func (x *SaveSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SaveSnapshotRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SaveSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSnapshotResponse) Reset() {
	*x = SaveSnapshotResponse{}
	mi := &file_evento_v1_store_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotResponse) ProtoMessage() {}

func (x *SaveSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SaveSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{22}
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateType string                 `protobuf:"bytes,1,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_evento_v1_store_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteSnapshotRequest) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_evento_v1_store_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evento_v1_store_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_evento_v1_store_proto_rawDescGZIP(), []int{24}
}

var File_evento_v1_store_proto protoreflect.FileDescriptor

const file_evento_v1_store_proto_rawDesc = "" +
	"\n" +
	"\x15evento/v1/store.proto\x12\tevento.v1\"\xd3\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\faggregate_id\x18\x02 \x01(\tR\vaggregateId\x12%\n" +
	"\x0eaggregate_type\x18\x03 \x01(\tR\raggregateType\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12$\n" +
	"\vrouting_key\x18\x06 \x01(\tH\x00R\n" +
	"routingKey\x88\x01\x01\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12/\n" +
	"\bmetadata\x18\b \x01(\v2\x13.evento.v1.MetadataR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x04R\ttimestamp\x12)\n" +
	"\x10timestamp_subsec\x18\n" +
	" \x01(\rR\x0ftimestampSubsecB\x0e\n" +
	"\f_routing_key\"\x86\x01\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04meta\x18\x02 \x03(\v2\x1d.evento.v1.Metadata.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"2\n" +
	"\bNewEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xad\x02\n" +
	"\fWriteRequest\x12%\n" +
	"\x0eaggregate_type\x18\x01 \x01(\tR\raggregateType\x12&\n" +
	"\faggregate_id\x18\x02 \x01(\tH\x00R\vaggregateId\x88\x01\x01\x12)\n" +
	"\x10original_version\x18\x03 \x01(\rR\x0foriginalVersion\x12$\n" +
	"\vrouting_key\x18\x04 \x01(\tH\x01R\n" +
	"routingKey\x88\x01\x01\x12/\n" +
	"\bmetadata\x18\x05 \x01(\v2\x13.evento.v1.MetadataR\bmetadata\x12+\n" +
	"\x06events\x18\x06 \x03(\v2\x13.evento.v1.NewEventR\x06eventsB\x0f\n" +
	"\r_aggregate_idB\x0e\n" +
	"\f_routing_key\"U\n" +
	"\rWriteResponse\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12!\n" +
	"\flast_version\x18\x02 \x01(\rR\vlastVersion\"\x8f\x01\n" +
	"\vEventFilter\x12%\n" +
	"\x0eaggregate_type\x18\x01 \x01(\tR\raggregateType\x12&\n" +
	"\faggregate_id\x18\x02 \x01(\tH\x00R\vaggregateId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01B\x0f\n" +
	"\r_aggregate_idB\a\n" +
	"\x05_name\"C\n" +
	"\n" +
	"RoutingKey\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\x9a\x01\n" +
	"\x04Args\x12\x19\n" +
	"\x05first\x18\x01 \x01(\rH\x00R\x05first\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x02 \x01(\tH\x01R\x05after\x88\x01\x01\x12\x17\n" +
	"\x04last\x18\x03 \x01(\rH\x02R\x04last\x88\x01\x01\x12\x1b\n" +
	"\x06before\x18\x04 \x01(\tH\x03R\x06before\x88\x01\x01B\b\n" +
	"\x06_firstB\b\n" +
	"\x06_afterB\a\n" +
	"\x05_lastB\t\n" +
	"\a_before\"\xb9\x01\n" +
	"\vReadRequest\x128\n" +
	"\vaggregators\x18\x01 \x03(\v2\x16.evento.v1.EventFilterR\vaggregators\x12;\n" +
	"\vrouting_key\x18\x02 \x01(\v2\x15.evento.v1.RoutingKeyH\x00R\n" +
	"routingKey\x88\x01\x01\x12#\n" +
	"\x04args\x18\x03 \x01(\v2\x0f.evento.v1.ArgsR\x04argsB\x0e\n" +
	"\f_routing_key\"D\n" +
	"\x04Edge\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12$\n" +
	"\x04node\x18\x02 \x01(\v2\x10.evento.v1.EventR\x04node\"\xc6\x01\n" +
	"\bPageInfo\x12*\n" +
	"\x11has_previous_page\x18\x01 \x01(\bR\x0fhasPreviousPage\x12\"\n" +
	"\rhas_next_page\x18\x02 \x01(\bR\vhasNextPage\x12&\n" +
	"\fstart_cursor\x18\x03 \x01(\tH\x00R\vstartCursor\x88\x01\x01\x12\"\n" +
	"\n" +
	"end_cursor\x18\x04 \x01(\tH\x01R\tendCursor\x88\x01\x01B\x0f\n" +
	"\r_start_cursorB\r\n" +
	"\v_end_cursor\"g\n" +
	"\fReadResponse\x12%\n" +
	"\x05edges\x18\x01 \x03(\v2\x0f.evento.v1.EdgeR\x05edges\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.evento.v1.PageInfoR\bpageInfo\"\x9f\x01\n" +
	"\x16LatestTimestampRequest\x128\n" +
	"\vaggregators\x18\x01 \x03(\v2\x16.evento.v1.EventFilterR\vaggregators\x12;\n" +
	"\vrouting_key\x18\x02 \x01(\v2\x15.evento.v1.RoutingKeyH\x00R\n" +
	"routingKey\x88\x01\x01B\x0e\n" +
	"\f_routing_key\"7\n" +
	"\x17LatestTimestampResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\xc8\x01\n" +
	"\x0eSubscribeStart\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\vaggregators\x18\x02 \x03(\v2\x16.evento.v1.EventFilterR\vaggregators\x12;\n" +
	"\vrouting_key\x18\x03 \x01(\v2\x15.evento.v1.RoutingKeyH\x00R\n" +
	"routingKey\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\rR\tchunkSizeB\x0e\n" +
	"\f_routing_key\"&\n" +
	"\fSubscribeAck\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"}\n" +
	"\x10SubscribeRequest\x121\n" +
	"\x05start\x18\x01 \x01(\v2\x19.evento.v1.SubscribeStartH\x00R\x05start\x12+\n" +
	"\x03ack\x18\x02 \x01(\v2\x17.evento.v1.SubscribeAckH\x00R\x03ackB\t\n" +
	"\amessage\"3\n" +
	"\n" +
	"EventBatch\x12%\n" +
	"\x05edges\x18\x01 \x03(\v2\x0f.evento.v1.EdgeR\x05edges\"6\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"z\n" +
	"\x12GetSnapshotRequest\x12%\n" +
	"\x0eaggregate_type\x18\x01 \x01(\tR\raggregateType\x12-\n" +
	"\x12aggregate_revision\x18\x02 \x01(\tR\x11aggregateRevision\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"X\n" +
	"\x13GetSnapshotResponse\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x13.evento.v1.SnapshotH\x00R\bsnapshot\x88\x01\x01B\v\n" +
	"\t_snapshot\"\xa7\x01\n" +
	"\x13SaveSnapshotRequest\x12%\n" +
	"\x0eaggregate_type\x18\x01 \x01(\tR\raggregateType\x12-\n" +
	"\x12aggregate_revision\x18\x02 \x01(\tR\x11aggregateRevision\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"\x16\n" +
	"\x14SaveSnapshotResponse\"N\n" +
	"\x15DeleteSnapshotRequest\x12%\n" +
	"\x0eaggregate_type\x18\x01 \x01(\tR\raggregateType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteSnapshotResponse2\x96\x04\n" +
	"\n" +
	"EventStore\x12:\n" +
	"\x05Write\x12\x17.evento.v1.WriteRequest\x1a\x18.evento.v1.WriteResponse\x127\n" +
	"\x04Read\x12\x16.evento.v1.ReadRequest\x1a\x17.evento.v1.ReadResponse\x12X\n" +
	"\x0fLatestTimestamp\x12!.evento.v1.LatestTimestampRequest\x1a\".evento.v1.LatestTimestampResponse\x12C\n" +
	"\tSubscribe\x12\x1b.evento.v1.SubscribeRequest\x1a\x15.evento.v1.EventBatch(\x010\x01\x12L\n" +
	"\vGetSnapshot\x12\x1d.evento.v1.GetSnapshotRequest\x1a\x1e.evento.v1.GetSnapshotResponse\x12O\n" +
	"\fSaveSnapshot\x12\x1e.evento.v1.SaveSnapshotRequest\x1a\x1f.evento.v1.SaveSnapshotResponse\x12U\n" +
	"\x0eDeleteSnapshot\x12 .evento.v1.DeleteSnapshotRequest\x1a!.evento.v1.DeleteSnapshotResponseB7Z5github.com/timayz/evento/clients/go/eventov1;eventov1b\x06proto3"

var (
	file_evento_v1_store_proto_rawDescOnce sync.Once
	file_evento_v1_store_proto_rawDescData []byte
)

func file_evento_v1_store_proto_rawDescGZIP() []byte {
	file_evento_v1_store_proto_rawDescOnce.Do(func() {
		file_evento_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evento_v1_store_proto_rawDesc), len(file_evento_v1_store_proto_rawDesc)))
	})
	return file_evento_v1_store_proto_rawDescData
}

var file_evento_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_evento_v1_store_proto_goTypes = []any{
	(*Event)(nil),                   // 0: evento.v1.Event
	(*Metadata)(nil),                // 1: evento.v1.Metadata
	(*NewEvent)(nil),                // 2: evento.v1.NewEvent
	(*WriteRequest)(nil),            // 3: evento.v1.WriteRequest
	(*WriteResponse)(nil),           // 4: evento.v1.WriteResponse
	(*EventFilter)(nil),             // 5: evento.v1.EventFilter
	(*RoutingKey)(nil),              // 6: evento.v1.RoutingKey
	(*Args)(nil),                    // 7: evento.v1.Args
	(*ReadRequest)(nil),             // 8: evento.v1.ReadRequest
	(*Edge)(nil),                    // 9: evento.v1.Edge
	(*PageInfo)(nil),                // 10: evento.v1.PageInfo
	(*ReadResponse)(nil),            // 11: evento.v1.ReadResponse
	(*LatestTimestampRequest)(nil),  // 12: evento.v1.LatestTimestampRequest
	(*LatestTimestampResponse)(nil), // 13: evento.v1.LatestTimestampResponse
	(*SubscribeStart)(nil),          // 14: evento.v1.SubscribeStart
	(*SubscribeAck)(nil),            // 15: evento.v1.SubscribeAck
	(*SubscribeRequest)(nil),        // 16: evento.v1.SubscribeRequest
	(*EventBatch)(nil),              // 17: evento.v1.EventBatch
	(*Snapshot)(nil),                // 18: evento.v1.Snapshot
	(*GetSnapshotRequest)(nil),      // 19: evento.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),     // 20: evento.v1.GetSnapshotResponse
	(*SaveSnapshotRequest)(nil),     // 21: evento.v1.SaveSnapshotRequest
	(*SaveSnapshotResponse)(nil),    // 22: evento.v1.SaveSnapshotResponse
	(*DeleteSnapshotRequest)(nil),   // 23: evento.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),  // 24: evento.v1.DeleteSnapshotResponse
	nil,                             // 25: evento.v1.Metadata.MetaEntry
}
var file_evento_v1_store_proto_depIdxs = []int32{
	1,  // 0: evento.v1.Event.metadata:type_name -> evento.v1.Metadata
	25, // 1: evento.v1.Metadata.meta:type_name -> evento.v1.Metadata.MetaEntry
	1,  // 2: evento.v1.WriteRequest.metadata:type_name -> evento.v1.Metadata
	2,  // 3: evento.v1.WriteRequest.events:type_name -> evento.v1.NewEvent
	5,  // 4: evento.v1.ReadRequest.aggregators:type_name -> evento.v1.EventFilter
	6,  // 5: evento.v1.ReadRequest.routing_key:type_name -> evento.v1.RoutingKey
	7,  // 6: evento.v1.ReadRequest.args:type_name -> evento.v1.Args
	0,  // 7: evento.v1.Edge.node:type_name -> evento.v1.Event
	9,  // 8: evento.v1.ReadResponse.edges:type_name -> evento.v1.Edge
	10, // 9: evento.v1.ReadResponse.page_info:type_name -> evento.v1.PageInfo
	5,  // 10: evento.v1.LatestTimestampRequest.aggregators:type_name -> evento.v1.EventFilter
	6,  // 11: evento.v1.LatestTimestampRequest.routing_key:type_name -> evento.v1.RoutingKey
	5,  // 12: evento.v1.SubscribeStart.aggregators:type_name -> evento.v1.EventFilter
	6,  // 13: evento.v1.SubscribeStart.routing_key:type_name -> evento.v1.RoutingKey
	14, // 14: evento.v1.SubscribeRequest.start:type_name -> evento.v1.SubscribeStart
	15, // 15: evento.v1.SubscribeRequest.ack:type_name -> evento.v1.SubscribeAck
	9,  // 16: evento.v1.EventBatch.edges:type_name -> evento.v1.Edge
	18, // 17: evento.v1.GetSnapshotResponse.snapshot:type_name -> evento.v1.Snapshot
	3,  // 18: evento.v1.EventStore.Write:input_type -> evento.v1.WriteRequest
	8,  // 19: evento.v1.EventStore.Read:input_type -> evento.v1.ReadRequest
	12, // 20: evento.v1.EventStore.LatestTimestamp:input_type -> evento.v1.LatestTimestampRequest
	16, // 21: evento.v1.EventStore.Subscribe:input_type -> evento.v1.SubscribeRequest
	19, // 22: evento.v1.EventStore.GetSnapshot:input_type -> evento.v1.GetSnapshotRequest
	21, // 23: evento.v1.EventStore.SaveSnapshot:input_type -> evento.v1.SaveSnapshotRequest
	23, // 24: evento.v1.EventStore.DeleteSnapshot:input_type -> evento.v1.DeleteSnapshotRequest
	4,  // 25: evento.v1.EventStore.Write:output_type -> evento.v1.WriteResponse
	11, // 26: evento.v1.EventStore.Read:output_type -> evento.v1.ReadResponse
	13, // 27: evento.v1.EventStore.LatestTimestamp:output_type -> evento.v1.LatestTimestampResponse
	17, // 28: evento.v1.EventStore.Subscribe:output_type -> evento.v1.EventBatch
	20, // 29: evento.v1.EventStore.GetSnapshot:output_type -> evento.v1.GetSnapshotResponse
	22, // 30: evento.v1.EventStore.SaveSnapshot:output_type -> evento.v1.SaveSnapshotResponse
	24, // 31: evento.v1.EventStore.DeleteSnapshot:output_type -> evento.v1.DeleteSnapshotResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_evento_v1_store_proto_init() }
func file_evento_v1_store_proto_init() {
	if File_evento_v1_store_proto != nil {
		return
	}
	file_evento_v1_store_proto_msgTypes[0].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[3].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[5].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[6].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[7].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[8].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[10].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[12].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[14].OneofWrappers = []any{}
	file_evento_v1_store_proto_msgTypes[16].OneofWrappers = []any{
		(*SubscribeRequest_Start)(nil),
		(*SubscribeRequest_Ack)(nil),
	}
	file_evento_v1_store_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evento_v1_store_proto_rawDesc), len(file_evento_v1_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evento_v1_store_proto_goTypes,
		DependencyIndexes: file_evento_v1_store_proto_depIdxs,
		MessageInfos:      file_evento_v1_store_proto_msgTypes,
	}.Build()
	File_evento_v1_store_proto = out.File
	file_evento_v1_store_proto_goTypes = nil
	file_evento_v1_store_proto_depIdxs = nil
}
