name: Publish

on:
  push:
    branches:
      - main
    paths-ignore: 
      - "**/Cargo.toml"
      - "Cargo.lock"
    tags:
      - '*'

jobs:
  cargo:
    uses: timayz/.github/.github/workflows/cargo-publish.yml@v3
    with:
      publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
