[package]
name = "quickstart"
version = "2.0.0-alpha.28"
edition.workspace = true
publish = false

[package.metadata.cargo-machete]
ignored = ["bitcode"]

[dependencies]
evento = { workspace = true, features = ["fjall"] }
anyhow.workspace = true
bitcode.workspace = true
tokio.workspace = true
tempfile = "3.27"
